include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    cancel_subscriptions: true
    close_sinks: true
    prefer_relative_imports: true
    avoid_relative_lib_imports: true
    prefer_single_quotes: true
    prefer_void_to_null: true
    avoid_type_to_string: true
    collection_methods_unrelated_type: true
    discarded_futures: false
    empty_statements: true
    hash_and_equals: true
    no_duplicate_case_values: true
    unnecessary_brace_in_string_interps: true
    avoid_classes_with_only_static_members: false
    avoid_void_async: true
    await_only_futures: true
    prefer_const_constructors: true

analyzer:
  language:
    strict-casts: true
    strict-raw-types: false
  errors:
    invalid_annotation_target: ignore
    lines_longer_than_80_chars: ignore
    missing_required_param: error
    fixme: ignore
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
    - lib/**/localization/generated/**.dart
