name: archi_explorer
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0-180.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.5
  provider: ^6.1.2
  flutter_screenutil: ^5.9.1
  device_preview:
    git:
      url: https://github.com/RuslanTsitser/flutter_device_preview.git
      path: device_preview
  feedback: ^3.1.0
  auto_size_text: ^3.0.0
  auto_route: ^8.1.3
  url_launcher: ^6.2.6
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.10+1
  in_app_review: ^2.0.9
  octo_image: ^2.0.0
  intl: any
  syncfusion_flutter_charts: ^25.2.4
  dots_indicator: ^3.0.0
  percent_indicator: ^4.2.3
  flutter_markdown: ^0.7.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.1
  path_provider: ^2.1.3
  photo_view: ^0.15.0
  collection: ^1.18.0
  syncfusion_flutter_calendar: ^25.2.6
  flutter_native_splash: ^2.4.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  build_runner: ^2.4.9
  auto_route_generator: ^8.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#362624"
  image: "assets/splash.png"
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svg/
