name: template
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0-180.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  dio: ^5.7.0
  url_launcher: ^6.3.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  intl: ^0.19.0
  js: ^0.7.1
  amplitude_flutter: ^3.16.6
  auto_route: ^9.2.2
  blur: ^4.0.0
  auto_size_text: ^3.0.0
  logger: ^2.5.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.5

  # uuid: ^4.5.1
  percent_indicator: ^4.2.4
  # share_plus: ^10.1.3
  collection: ^1.18.0

  flutter_bloc: ^8.1.6

  # flutter_screenutil: ^5.9.1
  device_preview:
    git:
      url: https://github.com/RuslanTsitser/flutter_device_preview.git
      path: device_preview

  in_app_review: ^2.0.10

  image_picker: ^1.1.2

  flutter_native_splash: ^2.4.4
  permission_handler: ^11.3.1

  #assets
  flutter_svg: ^2.0.16
  lottie: ^3.3.0
  octo_image: ^2.1.0

  # Firebase
  # firebase_core: ^3.9.0
  # cloud_firestore: ^5.6.0
  # firebase_auth: ^5.3.4
  # firebase_crashlytics: ^4.2.0
  # firebase_analytics: ^11.3.6

  # Attribution
  # apphud: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.14
  flutter_gen_runner: any
  flutter_lints: ^5.0.0
  intl_utils: ^2.8.7
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: true
  # ios: true
  image_path: "assets/app_icon.png"
  # min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/app_icon.png"

flutter_gen:
  output: lib/core/gen
  integrations:
    flutter_svg: true
    lottie: true

flutter_intl:
  enabled: true
  arb_dir: lib/core/localization/l10n
  output_dir: lib/core/localization/generated
  output_class: lib/core/localization/generated/l10n.dart

flutter:
  uses-material-design: true
  generate: true
  # assets:
  # - assets/
  # - assets/json/
  # - assets/images/
